### ISSUE TITLE
Resolve environment variables in yaml configuration

### ISSUE THREAD

**Issue by Sheshuk** [Sheshuk/snap-base#15]
Find all occurrences of _$VARNAME_ in the config file and replace it with value from the environment.

Use case: override some variables set in the config file without the need to change config.
Example: `node.yml`:
```yml
node:
     main:
          source:
              .zmq.recv: {address: ${ADDRESS}}
          steps:
              - .output.dump: { prefix: "recv from ${ADDRESS}" }
```
And it can be run as
``` shell
> ADDRESS="tcp://127.0.0.1:5000" snap node.yml
```
