### ISSUE TITLE
Improve yml config syntax

### ISSUE THREAD

**Issue by Sheshuk** [Sheshuk/snap-base#3]
Current (v0.1) syntax:

```yml
node:
    chain_start:
        source: obj@foo.bar.generator: {param1: 'value1'}
        elements:
            - obj@foo.bar.functor1: {param2: 'value2'}
            - obj@foo.bar.func
            - obj@foo.bar.functor2: {param3: 1.23, param4: obj@foo.bar.someobj}
        targets:
            - chain_branch1
            - chain_branch2

    chain_branch1:
        elements:
            - obj@foo.bar.stuff1     
        targets: 
            - chain_end

    chain_branch2:
        elements:
            - obj@foo.bar.stuff2     
            - obj@foo.bar.more_stuff2: {param4: 456}
        targets: 
            - chain_end

    chain_end:
        elements:
            - obj@foo.bar.save_all
```

**Comment by Sheshuk** [comment]
Desired:

```yaml
node:
    chain_start:
        source: foo.bar.generator: {param1: 'value1'}
        steps:
            - foo.bar.functor1: {param2: 'value2'}
            - foo.bar.func
            - foo.bar.functor2: {param3: 1.23, param4: obj@foo.bar.someobj }
        to:
            - chain_branch1
            - chain_branch2

    chain_branch1:
        steps:
            - foo.bar.stuff1     
        to: chain_end

    chain_branch2:
        steps:
            - foo.bar.stuff2     
            - foo.bar.more_stuff2: {param4: 456}
        to:  "chain_end"

    chain_end:
        steps:        
            - foo.bar.save_all
```

So changes:
* `elements` --> `steps`
* `targets` --> `to`
* No `obj@` required in the values of `steps` and `source` (but still needed in all other cases)
